### ISSUE TITLE
Force Computers SYS68k CPU-6A

### ISSUE THREAD

**Issue by toncho11** [shattered/linux-m68k#1]
Hi,

Would linux m-68K Linux run on  a Force Compyters SYS68k/CPU-6A rev 4.4 board?
Would it fit on the 4 EPROMS?

Specification:
• CPU-6A 68010 CPU (12,5MHz)
• 512 Kbyte of dynamic RAM o Wait States at 8MHz 1 Wait State at 12,5MHz Distributed hardware refresh every 15us
• 4 EPROM sockets provide 256 Kbyte space
• 3 serial communication ports (RS232 compatible)
• Parallel I/O interface to P2 connector
• Real Time Clock with on-board battery back-up
• 24-bit timer with 5-bit prescaler
• Local interrupt service via auto-vectoring
• Fully VMEbus IEEE 1014 standard compatible
• RESET and ABORT function switches
• Double Eurocard from factor
• Powerful real time Monitor/Debugger VMEPROM on board
• PDOS' Real Time Operating System optionally available
• Fully software and I/O signal compatible to the SYS68K1CPU-1 B series

**Comment by shattered** [comment]
Hi,

I don't think so.  Keep in mind that this is a very old, unmaintained fork and no one is working on it.
